/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Helvetica Neue',
          'Inter',
          'DM Sans',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        'display-l': ['56px', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        'h1': ['44px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'h2': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'h3': ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'h4': ['22px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'body-l': ['18px', { lineHeight: '1.55' }],
        'body-m': ['16px', { lineHeight: '1.55' }],
        'body-s': ['14px', { lineHeight: '1.55' }],
        'caption': ['12px', { lineHeight: '1.55' }],
      },
      colors: {
        brand: {
          primary: '#2575FC',
          ink: '#162B54',
        },
        light: {
          background: '#F7F9FC',
          surface: '#FFFFFF',
          'surface-subtle': '#F3F6FB',
          text: {
            primary: '#0B1220',
            secondary: '#334155',
            muted: '#64748B',
            inverse: '#FFFFFF',
          },
          border: {
            subtle: '#E6EAF2',
            strong: '#D7DEEA',
          },
          primary: {
            solid: '#2575FC',
            hover: '#1E63D8',
            active: '#184FB0',
            'soft-bg': '#EAF1FF',
            'soft-text': '#1E63D8',
          },
          accent: {
            violet: '#8B5CF6',
            pink: '#EC4899',
          },
          status: {
            success: '#16A34A',
            warning: '#F59E0B',
            danger: '#EF4444',
            info: '#2563EB',
          },
        },
        dark: {
          background: '#0B1220',
          surface: '#0F1A2E',
          'surface-subtle': '#101E38',
          text: {
            primary: '#EAF0FF',
            secondary: '#C7D2FE',
            muted: '#9AA7C2',
            inverse: '#0B1220',
          },
          border: {
            subtle: '#22304A',
            strong: '#2C3C5C',
          },
          primary: {
            solid: '#5B8DFF',
            hover: '#4D7DFF',
            active: '#3B68F0',
            'soft-bg': '#162449',
            'soft-text': '#C7D2FE',
          },
          accent: {
            violet: '#A78BFA',
            pink: '#F472B6',
          },
          status: {
            success: '#22C55E',
            warning: '#FBBF24',
            danger: '#F87171',
            info: '#60A5FA',
          },
        },
      },
      borderRadius: {
        'xs': '8px',
        'sm': '10px',
        'md': '14px',
        'lg': '18px',
        'xl': '24px',
        'pill': '999px',
      },
      boxShadow: {
        'card-light': '0 10px 30px -20px rgba(15, 23, 42, 0.18)',
        'card-hover-light': '0 18px 44px -22px rgba(15, 23, 42, 0.22)',
        'floating-light': '0 24px 60px -30px rgba(15, 23, 42, 0.28)',
        'focus-light': '0 0 0 4px rgba(37, 117, 252, 0.20)',
        'card-dark': '0 10px 30px -20px rgba(0, 0, 0, 0.55)',
        'card-hover-dark': '0 18px 44px -22px rgba(0, 0, 0, 0.62)',
        'floating-dark': '0 24px 60px -30px rgba(0, 0, 0, 0.70)',
        'focus-dark': '0 0 0 4px rgba(91, 141, 255, 0.22)',
      },
      spacing: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '30': '120px',
      },
      transitionDuration: {
        'fast': '150ms',
        'base': '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.2, 0, 0, 1)',
        'emphasized': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      maxWidth: {
        'container': '1120px',
      },
      letterSpacing: {
        'display': '-0.03em',
        'heading': '-0.02em',
        'overline': '0.08em',
      },
    },
  },
  plugins: [],
};
